services:
  integration-client:
    build: ./integration
    container_name: api-integration-client
    environment:
      - APP_URL=http://host.docker.internal:30080
      - PROMETHEUS_URL=http://host.docker.internal:30900
      - GRAFANA_URL=http://host.docker.internal:30300
      - GRAFANA_PASSWORD=admin123
    restart: unless-stopped
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"